"""Codex CLI credential handling — auth.json management and env var export."""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING, Any

from switcher.errors import AuthError
from switcher.utils import atomic_symlink, get_codex_dir, get_config_dir

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger("switcher.auth.codex")


def activate_apikey_profile(profile_dir: Path) -> None:
    """Activate a Codex API key profile.

    Steps:
    1. Atomic symlink auth.json → ~/.codex/auth.json
    2. Write OPENAI_API_KEY to env.sh

    Args:
        profile_dir: Path to the profile directory containing auth.json.
    """
    auth_file = profile_dir / "auth.json"
    if not auth_file.exists():
        raise AuthError(f"Missing auth.json in {profile_dir}")

    codex_dir = get_codex_dir()
    codex_dir.mkdir(parents=True, exist_ok=True)
    target = codex_dir / "auth.json"

    atomic_symlink(auth_file, target)

    api_key = extract_api_key(auth_file)
    if api_key:
        write_env_sh(gemini_key=None, codex_key=api_key)

    logger.info("Activated Codex API key profile from %s", profile_dir.name)


def activate_chatgpt_profile(profile_dir: Path) -> None:
    """Activate a Codex ChatGPT OAuth profile.

    Args:
        profile_dir: Path to the profile directory containing auth.json.
    """
    auth_file = profile_dir / "auth.json"
    if not auth_file.exists():
        raise AuthError(f"Missing auth.json in {profile_dir}")

    codex_dir = get_codex_dir()
    codex_dir.mkdir(parents=True, exist_ok=True)
    target = codex_dir / "auth.json"

    atomic_symlink(auth_file, target)
    write_env_sh(gemini_key=None, codex_key=None, clear_codex=True)
    logger.info("Activated Codex ChatGPT profile from %s", profile_dir.name)


def detect_auth_type(auth_json_path: Path) -> str:
    """Detect the auth type from a Codex auth.json file.

    Args:
        auth_json_path: Path to the auth.json file.

    Returns:
        'apikey' if OPENAI_API_KEY is present, 'chatgpt' if tokens are present.

    Raises:
        AuthError: If the file can't be parsed or has unknown format.
    """
    try:
        with auth_json_path.open("r", encoding="utf-8") as f:
            data: dict[str, Any] = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        raise AuthError(f"Cannot parse {auth_json_path}: {exc}") from exc

    if data.get("OPENAI_API_KEY"):
        return "apikey"
    if data.get("tokens"):
        return "chatgpt"
    raise AuthError(f"Unknown auth.json format in {auth_json_path}")


def extract_api_key(auth_json_path: Path) -> str | None:
    """Extract OPENAI_API_KEY from a Codex auth.json file.

    Args:
        auth_json_path: Path to the auth.json file.

    Returns:
        The API key string, or None if not present.
    """
    try:
        with auth_json_path.open("r", encoding="utf-8") as f:
            data: dict[str, Any] = json.load(f)
        key: str | None = data.get("OPENAI_API_KEY")
        return key
    except (json.JSONDecodeError, OSError):
        return None


def write_env_sh(
    gemini_key: str | None = None,
    codex_key: str | None = None,
    *,
    clear_gemini: bool = False,
    clear_codex: bool = False,
) -> None:
    """Generate or update env.sh with active API keys.

    Preserves existing keys for the other CLI when only one is provided.

    Args:
        gemini_key: Gemini API key to set, or None to preserve existing.
        codex_key: Codex/OpenAI API key to set, or None to preserve existing.
        clear_gemini: When True, remove Gemini env vars instead of preserving them.
        clear_codex: When True, remove Codex env vars instead of preserving them.
    """
    env_path = get_config_dir() / "env.sh"
    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Read existing values to preserve
    existing_gemini: str | None = None
    existing_codex: str | None = None
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("export GEMINI_API_KEY="):
                existing_gemini = line.split("=", 1)[1].strip('"').strip("'")
            elif line.startswith("export GOOGLE_API_KEY="):
                pass  # Will be regenerated from gemini_key
            elif line.startswith("export OPENAI_API_KEY="):
                existing_codex = line.split("=", 1)[1].strip('"').strip("'")

    final_gemini = None if clear_gemini else (
        gemini_key if gemini_key is not None else existing_gemini
    )
    final_codex = None if clear_codex else (
        codex_key if codex_key is not None else existing_codex
    )

    lines = ["# Auto-generated by ai-account-switcher — do not edit manually"]
    if final_gemini:
        lines.append(f'export GEMINI_API_KEY="{final_gemini}"')
        lines.append(f'export GOOGLE_API_KEY="{final_gemini}"')
    if final_codex:
        lines.append(f'export OPENAI_API_KEY="{final_codex}"')
    lines.append("")  # trailing newline

    env_path.write_text("\n".join(lines), encoding="utf-8")
    logger.debug("Updated env.sh")
